apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.servicename }}
spec:
  selector:
    app: {{ .Values.app }}
  ports:
    - protocol: {{ .Values.protocol }}
      port: {{ .Values.serviceport }}
      targetPort: {{ .Values.ports.containerPort }}
  type: {{ .Values.typeport }}
